### ISSUE TITLE
Language features

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hacspec-rust#6]
Collecting discussion points for hacspec language features.

- [x] `ByteSeq` don't have to be pre-allocated (allows to use `push`). `array`s are always pre-allocated.
- [ ] How to handle support for `struct` and `enum`? (see [hpke](/hacspec/hacspecs-rust/blob/master/src/hpke.rs))
- [ ] Support for function pointers to implement something like sha2? 
- [ ] Use `Option` or `Result` types for error handling?
- [ ] Secret VS Public types
  - [ ] How to write nice non-constant-time specs?
  - [ ] What's the default?
  - [ ] Should declassify always be explicit or is `into`/`from` ok?
  - [ ] Which operations are allowed on secret integers, e.g. indexing?
- [x] Use contracts? (see [aes.rs](/hacspec/hacspecs-rust/blob/master/src/aes.rs#L50))

**Comment by denismerigoux** [comment]
Hi Franziskus, here's a more PL point of view on those features.

* If you allow `push` on `ByteSeq`, then logically it behaves as a list (or vector) instead of behaving as a sequence. Reasoning on lists is notably more difficult because it is an inherently recursive data structure, whereas sequences have a fixed length (determined at allocation) are are more easy to reason with. In HACL*, we only use sequences.
* Formalizing struct and enums of basic datatypes is not hard, and we should add support for them as it improves readability.
* Why does SHA2 need function pointers ? Higher-order functions are not too difficult to formalize (we are used to them) but how to encode them with Rust without borrowing ?
* For secret integers, see my points here https://github.com/hacspec/hacspecs-rust/pull/6. The thing I don't understand is why it is important to write non-constant-time specs. I had the impression that constant-timedness was a key property for secure crypto implementations.
* For contracts, I think it's a good thing, and we can use the `contracts` crate. They can be formalized as pre/postconditions in F*.

**Comment by denismerigoux** [comment]
I also see you added new primitives with your last commits, like the ability to split arrays into chunks. If the features you add are not syntactic sugar on top of existing primitives, it will require additional formalization effort. Surely adding chunks as a new primitive is helpful and we should formalize it, but don't forget to tell us when you need to add something so that @floriangru and I are aware of what we need to formalize.
